import { AspectRatio } from "@/components/ui/aspect-ratio";
import { Metadata } from "next";
import Image from "next/image";

type Params = { params: Promise<{ id: string }> };
export async function generateMetadata({ params }: Params): Promise<Metadata> {
  const { id } = await params;
  return {
    title: `${id}`,
    description: "Generated by create next app",
    openGraph: {
      title: `${id}`,
      description: "Generated by create next app",
    }
  };
}

export default async function ArticleDetailPage({ params }: Params) {
  const { id } = await params;
  // 角色背景颜色
  const characterBgColors = [
    "bg-pink-400 dark:bg-pink-600",
    "bg-purple-400 dark:bg-purple-600",
    "bg-blue-400 dark:bg-blue-600",
    "bg-green-400 dark:bg-green-600",
    "bg-yellow-400 dark:bg-yellow-600",
    "bg-red-400 dark:bg-red-600"
  ];

  // 标签颜色映射
  const tagColors = [
    "bg-pink-600 dark:bg-pink-800",
    "bg-blue-600 dark:bg-blue-800",
    "bg-purple-600 dark:bg-purple-800",
    "bg-green-600 dark:bg-green-800",
    "bg-yellow-600 dark:bg-yellow-800",
    "bg-red-600 dark:bg-red-800",
    "bg-indigo-600 dark:bg-indigo-800",
    "bg-teal-600 dark:bg-teal-800"
  ];

  const gameData = {
    id: 1,
    title: "春风之恋 ~樱花盛开的季节~",
    originalTitle: "春風の恋 ~桜咲く季節~",
    releaseDate: "2023-04-15",
    developer: "ChieriSoft",
    publisher: "ChieriSoft",
    rating: 9.3,
    description: '《春风之恋》是一款以日本校园为背景的恋爱模拟游戏。玩家将扮演主角在樱花盛开的季节里，邂逅各种性格迥异的女主角，发展出各自不同的故事线。游戏融合了精美的立绘、感人的剧情和丰富的选择支，带给玩家沉浸式的视觉小说体验。故事发生在一个名为"樱花坂"的虚构小镇，主角因各种原因转学至此，开始了全新的校园生活...',
    tags: ["校园恋爱", "视觉小说", "青春", "日常", "治愈", "情感", "轻喜剧", "文艺"],
    characters: [
      {
        name: "樱井千夏",
        cv: "佐藤日和",
        desc: "班长，成绩优异，性格认真但有点傲娇。喜欢阅读和花道。"
      },
      {
        name: "星野美月",
        cv: "高桥礼奈",
        desc: "学妹，性格活泼开朗，总是充满活力。是学校啦啦队的成员。"
      },
      {
        name: "藤原惠",
        cv: "木村真纪",
        desc: "青梅竹马，温柔体贴，擅长料理。自小与主角一起长大。"
      },
      {
        name: "高桥结衣",
        cv: "田中花子",
        desc: "转学生，神秘冷漠，很少与人交流。拥有出色的音乐才能。"
      },
      {
        name: "中村小雪",
        cv: "山本美咲",
        desc: "学姐，文学社社长，沉稳成熟。喜欢写小说，有洞察力。"
      },
      {
        name: "佐藤亮介",
        cv: "鈴木大輔",
        desc: "主角的好友，性格开朗，是学校棒球部的王牌投手。"
      }
    ],
    screenshots: [1, 2, 3, 4, 5]
  };

  return (
    <>
      <div className="flex gap-4 flex-1 w-full"> {/* 修改为w-auto */}
        {/* 封面信息 */}
        <div className="flex w-1/4 flex-col space-y-2 w-auto"> {/* 移除固定宽度 */}
          <AspectRatio ratio={4 / 6} className="overflow-hidden rounded relative bg-gray-100 dark:bg-gray-800">
            <Image
              src="https://t.alcy.cc/pc"
              alt="游戏封面图片"
              width={200}
              height={266}  // 3:4比例的高度
              className="object-cover w-full h-full"
            />
          </AspectRatio>
        </div>
        <div className="flex flex-col flex-1">

        </div>
      </div>
    </>

  );
}