import { Metadata } from "next";

type Params = { params: Promise<{ id: string }> };
export async function generateMetadata({ params }: Params): Promise<Metadata> {
  const { id } = await params;
  return {
    title: `${id}`,
    description: "Generated by create next app",
    openGraph: {
      title: `${id}`,
      description: "Generated by create next app",

    }
  };
}
export default async function ArticleDetailPage({ params }: Params) {
  const { id } = await params;
  return <div>{id}</div>;
}